### ISSUE TITLE
Orlando Indie Hackers #1 Checklist

### ISSUE THREAD

**Issue by bijanbwb** [orlando-indie-hackers/home#1]
### Prep

- [x] Set a Tentative Date for Meeting
  - Monday August 12th (6:00pm - 8:00pm)
- [x] Create Event on Meetup.com
  - [Orlando Indie Hackers #1](https://www.meetup.com/orlando-indie-hackers/events/263258162/)
- [x] Four weeks before: Find a venue
  - [VentureX Coworking Space Downtown Orlando](https://venturex.com/locations/florida/downtown-orlando/)
- [x] One week before: Send out meeting announcement
  - [x] Include Date, Topics, Location, Contact Info, Inclusivity.
  - [x] Post to [Indie Hackers Meetup Section](https://www.indiehackers.com/meetups/new)
  - [x] OrlandoDevs Slack `#meetups` Channel
- [x] One week before: Verify event with venue
- [x] Day before: Send out meeting announcement
  - [x] Email [announcement](https://www.meetup.com/orlando-indie-hackers/messages/boards/thread/52379166) through Meetup.com for everyone that has RSVPed

### Event

- [x] Order Pizzas and Drinks for Meetup [Optional]
- [x] Prep Short [Presentation](https://github.com/orlando-indie-hackers/home/blob/master/slides/first-meeting.pdf) [Optional]
- [x] Pack any dongles, adapters, chargers, etc.
- [x] **Remember to take pictures!**

### Sharing

- [x] Post [picture](https://www.meetup.com/orlando-indie-hackers/photos/30259872/) to Meetup.com
- [x] Post thanks and quick meeting summary to [OrlandoDevs Slack](https://orlandodevs.com/)
- [x] Post a [quick tweet](https://twitter.com/bijanbwb/status/1161263657826881538) to Twitter
- [x] Post to [Indie Hackers Slack](https://twitter.com/bijanbwb/status/1161263657826881538) community

**Comment by bijanbwb** [comment]
Working on next month's checklist here: https://github.com/orlando-indie-hackers/home/issues/3
