### ISSUE TITLE
Orlando Indie Hackers #2 Checklist

### ISSUE THREAD

**Issue by bijanbwb** [orlando-indie-hackers/home#3]
### Prep

- [x] Set a Tentative Date for Meeting
  - ~~September 16th (6:00pm - 8:00pm)~~
  - September 17th (6:00pm - 8:00pm)
- [x] Create Event on Meetup.com
  - [Orlando Indie Hackers #2](https://www.meetup.com/orlando-indie-hackers/events/264315704)
- [x] Post to [Indie Hackers Meetup Section](https://www.indiehackers.com/meetups/new)
  - [Orlando Indie Hackers #2](https://www.indiehackers.com/meetups/42bdd382a9/)
- [x] Three weeks before: Find a venue
  - [VentureX Coworking Space Downtown Orlando](https://venturex.com/locations/florida/downtown-orlando/)
- [x] Two weeks before: Post to Meetup and announce.
- [x] Two weeks before: Post to `#indiehackers` channel.
- [x] One week before: Send out meeting announcements
  - [x] Include Date, Topics, Location, Contact Info, Inclusivity.
  - [x] OrlandoDevs Slack `#meetups` Channel
- ~Day before: Send out meeting announcement ([template](https://www.meetup.com/orlando-indie-hackers/messages/boards/thread/52379166))~

### Event

- [x] Order Pizzas and Drinks for Meetup
- [x] Prep Short Presentation ([template](https://github.com/orlando-indie-hackers/home/blob/master/slides/first-meeting.pdf))
- [x] Pack any stickers dongles, adapters, chargers, etc.
- [x] **Remember to take pictures!**

### Sharing

- [x] Post picture to Meetup.com
- [x] Post thanks and quick meeting summary to OrlandoDevs Slack
- [x] Post to Twitter
- [x] Post recap to Indie Hackers Slack
