### ISSUE TITLE
Orlando Indie Hackers #3 Checklist

### ISSUE THREAD

**Issue by bijanbwb** [orlando-indie-hackers/home#5]
### Inbox

- [ ] Reach out to previous attendees!
- [ ] Come up with less shitty titles than numbered events!

### Prep

- [ ] Set a Tentative Date for Meeting
  - October 29th (6:00pm - 8:00pm)
- [ ] Create Event on Meetup.com
- [ ] Post to [Indie Hackers Meetup Section](https://www.indiehackers.com/meetups/new)
- [ ] Three weeks before: Find a venue
- [ ] Two weeks before: Post to Meetup and announce.
- [ ] Two weeks before: Post to `#indiehackers` channel.
- [ ] One week before: Send out meeting announcements
  - [ ] Include Date, Topics, Location, Contact Info, Inclusivity.
  - [ ] OrlandoDevs Slack `#meetups` Channel
- Day before: Send out meeting announcement ([template](https://www.meetup.com/orlando-indie-hackers/messages/boards/thread/52379166))

### Event

- [ ] Order Pizzas and Drinks for Meetup
- [ ] Prep Short Presentation ([template](https://github.com/orlando-indie-hackers/home/blob/master/slides/first-meeting.pdf))
- [ ] Pack any stickers dongles, adapters, chargers, etc.
- [ ] **Remember to take pictures!**

### Sharing

- [ ] Post picture to Meetup.com
- [ ] Post thanks and quick meeting summary to OrlandoDevs Slack
- [ ] Post to Twitter
- [ ] Post recap to Indie Hackers Slack
